version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t g4g-profile-scrapper:latest .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUBUSER" --password-stdin
            docker image tag g4g-profile-scrapper:latest "$DOCKERHUBUSER"/scrapper:$(git rev-parse --short HEAD)
            docker push sgarg95/scrapper:$(git rev-parse --short HEAD)
      
      - add_ssh_keys:
          fingerprints:
            - "a3:9d:3c:7d:0a:f3:a5:36:23:da:c6:4f:d4:59:c9:75:a0:6e:61:bb"

      - run: 
          name: Install Docker on EC2
          command: |
            ssh -i /.ssh/id_rsa_a39d3c7d0af3a53623dac64fd459c975a06e61bb ec2-user@ec2-3-16-66-174.us-east-2.compute.amazonaws.com
            sudo yum install docker
            sudo service start docker
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUBUSER" --password-stdin
            sudo docker pull sgarg95/scrapper:$(git rev-parse --short HEAD)
  run_tests:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install -r requirements.txt
      - run:
          name: Run server
          command: python3 app.py
          background: true
      - run:
          name: Run unit tests
          command: |
            pytest 
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - deploy
      - run_tests:
          requires:
            - deploy